### ISSUE TITLE
Problemas com Itu/_pk0024.01

### ISSUE THREAD

**Issue by crebollobr** [digital-guard/preserv-BR#109]
Problema 01

https://github.com/digital-guard/preserv-BR/tree/main/data/SP/Itu/_pk0024.01

Parcel precisa de opção a mais no comando ogr2ogr

Modificação no makefile linha 332 adicionar -nlt CONVERT_TO_LINEAR -nlt PROMOTE_TO_MULTI

sudo docker run --rm --network host -v $(sandbox):/tmp osgeo/gdal ogr2ogr -lco GEOMETRY_NAME=geom -overwrite -f "PostgreSQL" PG:" dbname='$(pg_db)' host='localhost' port='5432' user='postgres' " "/tmp/LOGRADOURO_2019.tab"  -nln pk7600002401201_p2_via -nlt CONVERT_TO_LINEAR -nlt PROMOTE_TO_MULTI

**Comment by crebollobr** [comment]
Problema 02

A camada via as ruas não tem continuidade


![image](https://user-images.githubusercontent.com/22559999/169667596-928a7572-87a3-4042-9cad-f06d7570eb63.png)

**Comment by 0e1** [comment]
> Problema 01

Estendi o uso de `method_opts` para o método `ogr2ogr`, então você pode usar:

`method_opts: -nlt CONVERT_TO_LINEAR -nlt PROMOTE_TO_MULTI`

junto com o método ogr2ogr.

Eu troquei a chave `extension` pela chave `codec`.

Assim, os respectivos layers ficaram assim:

```
  parcel:
        subtype: full
        method: ogr2ogr
        file: 1
        sql_select: ['Bairro as nsvia_name','Logradouro AS via_name','Numero AS house_number', 'geom']
        orig_filename: lotes_Itu
        codec: TAB
  via:
        subtype: full
        method: ogr2ogr
        file: 2
        sql_select: ['Logradouro AS via_name', 'geom']
        orig_filename: LOGRADOURO_2019
        codec: TAB
        method_opts: -nlt CONVERT_TO_LINEAR -nlt PROMOTE_TO_MULTI
```

Essas alterações não afetem em nada os arquivos gerados.
