### ISSUE TITLE
tabname e label inconsistentes

### ISSUE THREAD

**Issue by ppKrauss** [digital-guard/preserv-BR#19]
Conferir esse tipo de pronblema: tipo de layer não bate com tabname. Exemplo de [AC/RioBranco/_pk046/make_conf](https://github.com/digital-guard/preserv-BR/blob/main/data/AC/RioBranco/_pk046/make_conf.yaml):

```
block:
        subtype: full
        method: shp2sql
        p: 2b
        file: 2
        tabname:  via
```

Uma opção seria não configurar `tabname` quando o layer pode ser usado como parte do nome, neste caso *pk046_block* seria um tabname default sem necessidade de definição.
