### ISSUE TITLE
preserv-BR/data/PR/Araucaria/_pk067

### ISSUE THREAD

**Issue by crebollobr** [digital-guard/preserv-BR#24]
Refazer preserv-BR/data/PR/Araucaria/_pk067
Join

**Comment by crebollobr** [comment]
Como fazer join de nsvia cidade e nsvia rural?
Ou não é possível?

**Comment by ppKrauss** [comment]
Não se trata do conceito de SQL-JOIN mas de SQL-UNION. Sim, a UNION tem sido feita pelo método de ingestão, vide exemplo de [São Paulo](https://github.com/digital-guard/preserv-BR/blob/main/data/SP/SaoPaulo/_pk0033.01/make_conf.yaml) que uniu bairros. @0e1 por favor documentar como foi feito isso, e qual a melhor prática no make_conf.

**Comment by ppKrauss** [comment]
Sugestões de encaminhamento:

@0e1  implementar novo template se for o caso interpretando que é insert cumulativo de dois shapfiles, declarados no make_conf como array, `orig_filename: [Bairros, Localidades Rurais]`. Oportuno lembrar que não precisamos mais das declarações de `p: xx` dentro dos layers (o JSON pré-processado deveria fazer isso).

@crebollobr corrigir a referência na versão atual do [make_conf](https://github.com/digital-guard/preserv-BR/blob/main/data/PR/Araucaria/_pk0061.01/make_conf.yaml), todos  os layers são relativos a `file: 1`, não existe *file 3*.

**Comment by 0e1** [comment]
O insert cumulativo para um array em `orig_filename` está quase pronto.

Alguns problemas:
- Para uma ingestão de vários arquivos em um layer, a tabela [ingest.donated_PackComponent](https://github.com/digital-guard/preserv/blob/main/src/ingest-step1-ini.sql#L226) pode ter

  `UNIQUE(ftid,hash_md5),`

   mas não pode ter

  `UNIQUE(packvers_id,ftid,is_evidence)`.

  `UNIQUE(packvers_id,ftid,hash_md5)` ou `UNIQUE(packvers_id,ftid,hash_md5,is_evidence)` não seria suficiente para essa tabela?

- Reparar que `sql_select` de `nsvia` e `nsvia: # rurais` são ligeiramente diferentes. _Bairros_ possuem coluna `nome` e _Localidades Rurais_ possuem coluna _nomes_ conforme [readme](https://github.com/digital-guard/preserv-BR/tree/main/data/PR/Araucaria/_pk0061.01#readme) e visto nos dados. Assim, nesse caso,`sql_select` deve ser diferente para cada arquivo no array. Devemos tornar possível um array em `sql_select` ou `sql_view`? Tornar iguais os nomes das colunas? Um `method` especifico para esse caso com duas chaves `sql_view`?

```
 nsvia:
    subtype: full
    method: shp2sql
    file: 1
    sql_select: ['gid', 'nome AS ns_name', 'geom']
    orig_filename: Bairros

  nsvia: # rurais
    subtype: full
    method: shp2sql
    file: 1
    sql_select: ['gid', 'nomes AS ns_name', 'geom']
    orig_filename: Localidades Rurais
```

Observação: se [ingest.donated_PackComponent](https://github.com/digital-guard/preserv/blob/main/src/ingest-step1-ini.sql#L226) não tiver a restrição `UNIQUE(packvers_id,ftid,is_evidence)` e `sql_view` for uma só, a ingestão de um array em `orig_filename` funciona sem problemas.

**Comment by 0e1** [comment]
Situação resolvida por https://github.com/digital-guard/preserv/commit/8a4231c9822b44b9a1b9347b71a78c8f29d1a14a e por https://github.com/digital-guard/preserv-BR/commit/374c758888fb8f89183180d95251a19ffafd580f.

Usei a ideia da _zip_. Os arrays `sql_select` e `orig_filename` são zipados e transformados em uma lista. Os [templates mustache](https://github.com/digital-guard/preserv/tree/main/src/maketemplates) fazem o restante, para gerar o código no _makefile_.

Resultado final no [make_conf](https://github.com/digital-guard/preserv-BR/blob/main/data/PR/Araucaria/_pk0061.01/make_conf.yaml#L23):

```
  nsvia:
    subtype: full
    method: shp2sql
    file: 1
    sql_select: [['gid', 'nome AS ns_name', 'geom'],['gid', 'nomes AS ns_name', 'geom']]
    orig_filename: ["Bairros","Localidades Rurais"]
```

Lembretes para documentação:
- Arrays devem ter mesma dimensão;
- A ordem nos arrays importa;
- Implementado para `sql_select` e não implementado para `sql_view`;
- Apenas para `method: shp2sql`;
- `orig_filename` e `sql_select` continuam podendo ser uma string ou um array simples, respectivamente.
